version: 2

models:
  #------------------------------------------------------------------ stg_orders Model ----------------------------------------------------------#
  - name: stg_orders
    description: '{{ doc("stg_orders_description") }}'
    columns:
      - name: O_ORDERKEY
        description: Unique identifier for each order in the dataset.
        tests:
          - not_null
          - unique
        data_type: number

      - name: C_CUSTKEY
        description: A unique identifier for the customer, used to establish relationships between the customer and their orders.
        data_type: number

      - name: C_NAME
        description: The name of the customer associated with the order. This column is sourced from the CUSTOMER table in the Snowflake sample data.
        data_type: varchar

      - name: O_ORDERDATE
        description: The date on which the order was placed.
        data_type: date

      - name: order_year
        description: The year extracted from the order date (O_ORDERDATE), representing the year in which the order was placed.
        data_type: number

      - name: O_TOTALPRICE
        description: The total price of the order, representing the monetary value of the transaction.
        data_type: number
        
      - name: c_nationkey
        description: The unique identifier for the nation associated with the customer. This key links the customer to their respective nation in the dataset.
        data_type: number

  #------------------------------------------------------------------ customer_revenue Model ----------------------------------------------------------#

  - name: customer_revenue
    description: '{{ doc("customer_revenue_description") }}'
    columns:
      - name: C_CUSTKEY
        description: Unique identifier for a customer, used to associate customer information with their orders and revenue.
        tests:
          - not_null
          - unique
        data_type: number

      - name: C_NAME
        description: The name of the customer, representing the unique identifier for the customer in the dataset.
        data_type: varchar

      - name: customer_revenue
        description: The total revenue generated by each customer, calculated as the sum of the order prices for all orders associated with the customer. Order prices are derived by applying discounts to the extended price of line items.
        data_type: number

  #------------------------------------------------------------------ customer_revenue Model ----------------------------------------------------------#

  - name: yearly_revenue
    description: '{{ doc("yearly_revenue_description") }}'
    columns:
      - name: yearly_revenue
        description: The total revenue generated for each year, calculated as the sum of the extended price of all line items after applying the discount.
        tests:
          - not_null
          - unique
        data_type: number

      - name: year
        description: The year in which the orders were placed, derived from the 'order_year' column in the 'stg_orders' table.
        data_type: number
  #------------------------------------------------------------------ revenue_per_nation Model ----------------------------------------------------------#

  - name: revenue_per_nation
    description: '{{doc("revenue_per_nation_description")}}'
    columns:
      - name: n_name
        description: The name of the nation, derived from the Nations table in the tpch_db.dev schema.
        data_type: varchar

      - name: revenue_per_nation
        description: The total revenue generated per nation, calculated as the sum of the extended price multiplied by (1 - discount) for all orders associated with a nation.
        data_type: number
