version: 2

models:
  #------------------------------------------------------------------ tests related to dim_listings_cleansed ----------------------------------------------------------#
  - name: stg_orders
    description: |
      This staging model consolidates data from the orders and customer tables 
      to provide a unified view of order details, including customer name, 
      order year, and total price.
    columns:
      - name: O_ORDERKEY
        tests:
          - not_null
          - unique

        description: Unique identifier for each order in the dataset.
        data_type: number

      - name: C_CUSTKEY
        description: A unique identifier for the customer, used to establish relationships between the customer and their orders.
        data_type: number

      - name: C_NAME
        description: The name of the customer associated with the order. This column is sourced from the CUSTOMER table in the Snowflake sample data.
        data_type: varchar

      - name: O_ORDERDATE
        description: The date on which the order was placed.
        data_type: date

      - name: order_year
        description: The year extracted from the order date (O_ORDERDATE), representing the year in which the order was placed.
        data_type: number

      - name: O_TOTALPRICE
        description: The total price of the order, representing the monetary value of the transaction.
        data_type: number

  - name: customer_revenue
    description: |
                  The customer_revenue model calculates the total revenue generated by each customer.
                  It aggregates the extended price of line items, adjusted for discounts, across all orders associated with a customer. 
                  The model joins data from the CUSTOMER, ORDERS, and LINEITEM tables to produce a summary of revenue per customer.
    columns:
      - name: C_CUSTKEY
        description: Unique identifier for a customer, used to associate customer information with their orders and revenue.
        tests:
          - not_null
          - unique
        data_type: number

      - name: C_NAME
        description: The name of the customer, representing the unique identifier for the customer in the dataset.
        data_type: varchar

      - name: customer_revenue
        description: The total revenue generated by each customer, calculated as the sum of the order prices for all orders associated with the customer. Order prices are derived by applying discounts to the extended price of line items.
        data_type: number
